# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Texture-Playground' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod "Texture"

  # Pods for Texture-Playground

  target 'Texture-PlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Texture-PlaygroundUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
